"use client";

import {
  EVENT_GROUP_CHAT_UPDATE_HEADING,
  type EventGroupChatUpdateChange,
} from "@/lib/events/eventGroupChatUpdateMessage";

/**
 * Body of an event-update system card.
 *
 * Reads top-down as "what kind of notice → which field → what it is now".
 * The old value is deliberately the quietest thing in the row: it's context
 * for the change, not the change itself, so it takes the muted token while
 * the new value keeps full-strength text and a medium weight.
 *
 * Colour tokens rather than opacity: this only ever renders on the fixed
 * `bg-surface-raised` card, so contrast is known here. The previous treatment
 * shared markup between a primary-filled bubble and a surface one and had to
 * use opacity to stay legible on both — that constraint is gone now that the
 * card owns its own background.
 */
export default function EventUpdateMessageContent({
  changes,
}: {
  changes: EventGroupChatUpdateChange[];
}) {
  return (
    <div className="flex flex-col gap-2">
      {/* Tiny uppercase accent label — FTC's established section-label
       * treatment, and the clearest "this was generated by the app" signal
       * available without adding an icon. */}
      <p className="text-[10px] font-semibold uppercase tracking-[0.08em] text-ftc-primary">
        {EVENT_GROUP_CHAT_UPDATE_HEADING}
      </p>

      <ul className="flex flex-col gap-2.5">
        {changes.map((change) => (
          <li key={change.label} className="flex flex-col gap-0.5">
            <span className="text-[10px] font-semibold uppercase tracking-[0.06em] text-ftc-text-muted">
              {change.label}
            </span>
            <span className="text-[13px] leading-snug break-words">
              <span className="text-ftc-text-muted">{change.from}</span>
              <span aria-hidden="true" className="px-1 text-ftc-text-muted">
                →
              </span>
              <span className="font-medium text-ftc-text">{change.to}</span>
            </span>
          </li>
        ))}
      </ul>
    </div>
  );
}
