"use client";

import Link from "next/link";
import LegalPageShell, {
  LegalList,
  LegalSection,
} from "@/app/components/legal/LegalPageShell";
import {
  DATA_HOSTING_REGION,
  LEGAL_CONTACT_EMAIL,
  LEGAL_LAST_UPDATED,
  LEGAL_OPERATOR,
} from "@/lib/legal";

/**
 * Privacy Policy for the Follow The Crowd private beta.
 *
 * Every statement here was checked against the code: the fields actually stored,
 * who can actually read them, the third parties actually used, and what account
 * deletion actually does. If the product changes, this changes with it — do not
 * let it drift into describing something the app does not do.
 */
export default function PrivacyPage() {
  return (
    <LegalPageShell title="Privacy Policy" lastUpdated={LEGAL_LAST_UPDATED}>
      <p>
        Follow The Crowd (&ldquo;FTC&rdquo;) is operated by {LEGAL_OPERATOR}. This policy
        explains what personal information FTC collects, who can see it, where it is stored,
        and what happens when you delete your account. It is written to align with the
        Australian Privacy Principles.
      </p>

      <LegalSection title="What FTC collects">
        <p className="font-semibold text-ftc-text">Account</p>
        <p>
          Your email address and password, handled by our authentication provider. FTC signs
          you in with email and password only — there is no social login.
        </p>

        <p className="mt-3 font-semibold text-ftc-text">Profile</p>
        <p>
          Whatever you choose to put on your profile: username, display name, bio, genre,
          location, profile image, artist or brand name, links to Instagram, TikTok,
          SoundCloud or a website, and the availability and past-work details relevant to your
          role.
        </p>
        <p>
          Location on your profile is <span className="font-semibold text-ftc-text">text you
          type</span> — for example a city. FTC does not collect GPS or device location.
        </p>

        <p className="mt-3 font-semibold text-ftc-text">What you create and send</p>
        <LegalList
          items={[
            "Direct messages and Crew Chat messages, including image attachments and reactions",
            "Events you create, including cover images, venue details and run sheets",
            "Booking requests and booking plans, including any fee you record and notes you add",
            "Read receipts, so unread counts work",
            "Notifications generated by the above",
            "Blocks and reports you make",
          ]}
        />
      </LegalSection>

      <LegalSection title="What FTC does not collect">
        <LegalList
          items={[
            "No payment or card details. FTC does not process payments.",
            "No analytics, advertising or tracking. There is no analytics SDK in the app.",
            "No device GPS location.",
            "No date of birth. Age is a confirmation you give at signup, not information we store about you.",
          ]}
        />
      </LegalSection>

      <LegalSection title="Who can see your information">
        <p className="font-semibold text-ftc-text">Your profile</p>
        <p>
          Profile information is visible to other signed-in FTC users. That is how promoters
          find DJs and how DJs see who is booking them. Treat your profile as public within
          FTC and only put there what you are comfortable other users seeing.
        </p>

        <p className="mt-3 font-semibold text-ftc-text">Your messages and bookings</p>
        <p>
          Direct messages are visible to you and the person you are talking to. Crew Chat
          messages are visible to the crew for that event — the planner and the DJs booked on
          it. Booking requests are visible to the promoter and DJ involved. Event details and
          run sheets are visible to the people connected to that event.
        </p>

        <p className="mt-3 font-semibold text-ftc-text">Who else</p>
        <p>
          {LEGAL_OPERATOR} can access data held in the systems below where necessary to run
          FTC, fix problems, or review a report. Your information is not sold, and it is not
          shared with anyone else except the service providers listed here or where required
          by law.
        </p>
      </LegalSection>

      <LegalSection title="Service providers">
        <LegalList
          items={[
            "Supabase — authentication, database, file storage and realtime updates. This is where your account, profile, messages, bookings and uploads are stored.",
            "Vercel — hosts and serves the application.",
            "Google Maps and Places — used to show and search venue locations. Venue and location queries you make in the app are sent to Google to return results.",
          ]}
        />
        <p>
          These providers process information so FTC can operate. Each has its own privacy
          terms.
        </p>
      </LegalSection>

      <LegalSection title="Where your information is stored">
        <p>
          FTC&rsquo;s database, authentication and file storage are hosted in{" "}
          <span className="font-semibold text-ftc-text">{DATA_HOSTING_REGION}</span>, so
          personal information may be stored and processed outside Australia.
        </p>
        <p>
          Application hosting and the mapping services above may also process information
          outside Australia. Overseas providers are subject to the laws of the countries they
          operate in, which may differ from Australian privacy law.
        </p>
      </LegalSection>

      <LegalSection title="How long information is kept">
        <p>
          Your information is kept while your account is open. Content you delete inside the
          app — a message, an event — is removed as the app describes.
        </p>
      </LegalSection>

      <LegalSection title="Deleting your account">
        <p>You can request account deletion from Settings. When you do:</p>
        <LegalList
          items={[
            "Your login is deleted, and you can no longer sign in.",
            "Your profile is anonymised. Your name, bio, images, links and other profile details are cleared, and the profile shows as “Deleted User”.",
            "Your availability, notifications, read receipts, reactions, blocks, reports and saved event plans are deleted.",
          ]}
        />
        <p className="mt-3 font-semibold text-ftc-text">
          Messages and booking history involving other people are not deleted.
        </p>
        <p>
          They remain attributed to &ldquo;Deleted User&rdquo;. This is deliberate: deleting
          them would remove the other person&rsquo;s record of a conversation they took part
          in or a booking they relied on. If you want something specific removed, contact us
          and we will consider it against the effect on other users.
        </p>
      </LegalSection>

      <LegalSection title="Security">
        <p>
          Access to your data is restricted at the database level so that, in general, you
          reach your own data and the data of conversations, bookings and events you are part
          of. While FTC uses security controls to protect your information, no online service
          can guarantee absolute security.
        </p>
      </LegalSection>

      <LegalSection title="Accessing or correcting your information">
        <p>
          Most of your information can be viewed and edited directly in the app through your
          profile and settings. If you want a copy of what FTC holds about you, or believe
          something is wrong, contact us and we will respond within a reasonable time.
        </p>
      </LegalSection>

      <LegalSection title="Complaints">
        <p>
          If you think your privacy has been mishandled, contact us first at the address
          below. If you are not satisfied with the response, you can complain to the Office
          of the Australian Information Commissioner at oaic.gov.au.
        </p>
      </LegalSection>

      <LegalSection title="Changes to this policy">
        <p>
          This policy will change as FTC develops. The date at the top shows when it last
          changed.
        </p>
      </LegalSection>

      <LegalSection title="Contact">
        <p>
          Privacy questions and requests:{" "}
          <a
            href={`mailto:${LEGAL_CONTACT_EMAIL}`}
            className="font-semibold text-ftc-primary hover:underline"
          >
            {LEGAL_CONTACT_EMAIL}
          </a>
        </p>
        <p>
          See also the{" "}
          <Link href="/terms" className="font-semibold text-ftc-primary hover:underline">
            Terms &amp; Conditions
          </Link>
          .
        </p>
      </LegalSection>
    </LegalPageShell>
  );
}
