-- Phase 2c Baseline Migration: Pre-001 Schema Bootstrap (CORRECTED)
-- File: 20250101000000_baseline_phase2c.sql
--
-- Purpose: Defines the complete schema required BEFORE migrations 001–010 execute.
-- This enables fresh database bootstrap: `migration reset` or fresh deploy will start
-- from this baseline and apply migrations 001–010 on top.
--
-- Prerequisites: Supabase Auth (email/password) must be enabled.
-- Does NOT create: auth schema, auth roles, or Supabase system objects (publications).
-- Does NOT include: any objects created by migrations 001–010.
--
-- Idempotent: safe to re-run using IF NOT EXISTS, CREATE OR REPLACE, etc.
--
-- CORRECTIONS APPLIED (vs proposed baseline):
-- 1. Removed creation of supabase_realtime publication (Supabase infrastructure)
-- 2. Fixed event_run_sheet_rows table (13 columns, not 4)
-- 3. Added can_view_event_run_sheet() function
-- 4. Added is_event_crew_member() function
-- 5. Added is_event_crew_member_for_message() function
-- 6. Added message_attachments table
-- 7. Added get_event_crew_participant_ids() function

-- ============================================================================
-- SCHEMA & ROLES
-- ============================================================================

grant usage on schema public to authenticated;

-- ============================================================================
-- PUBLIC.USERS
-- ============================================================================

create table if not exists public.users (
  id bigint primary key generated by default as identity,
  created_at timestamptz not null default now(),
  user_id text,
  role text,
  onboarding_complete boolean default false,
  display_name text
);

alter table public.users
  drop constraint if exists users_role_check;

alter table public.users
  add constraint users_role_check
  check (role is null or role in ('dj', 'promoter', 'both'));

create unique index if not exists users_user_id_key on public.users (user_id);

-- ============================================================================
-- PUBLIC.BOOKING_PLANS
-- ============================================================================

create table if not exists public.booking_plans (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz not null default now(),
  owner_id text not null,
  name text not null,
  event_name text not null,
  venue text not null,
  event_date text not null,
  set_time text not null,
  fee text not null,
  notes text not null default ''
);

create index if not exists booking_plans_owner_id_idx
  on public.booking_plans (owner_id);

-- ============================================================================
-- PUBLIC.CONVERSATIONS (for DM flow)
-- ============================================================================

create table if not exists public.conversations (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz not null default now()
);

-- ============================================================================
-- PUBLIC.CONVERSATION_MEMBERS
-- ============================================================================

create table if not exists public.conversation_members (
  conversation_id uuid not null references public.conversations (id) on delete cascade,
  user_id text not null,
  created_at timestamptz not null default now(),
  primary key (conversation_id, user_id)
);

-- ============================================================================
-- PUBLIC.BOOKING_REQUESTS
-- ============================================================================

create table if not exists public.booking_requests (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz not null default now(),
  sender_id text not null,
  recipient_id text not null,
  conversation_id uuid not null references public.conversations (id),
  event_id uuid,
  event_name text not null,
  venue text not null,
  event_date text not null,
  set_time text not null,
  fee text not null,
  notes text not null default '',
  status text not null default 'pending',
  archived_at timestamptz null,
  rate_mode text not null default 'fixed',
  proposed_rate integer null,
  proposed_rate_status text,
  proposed_rate_note text null,
  proposed_rate_at timestamptz
);

alter table public.booking_requests
  drop constraint if exists booking_requests_status_check;

alter table public.booking_requests
  add constraint booking_requests_status_check
  check (status in ('pending', 'accepted', 'declined', 'cancelled'));

alter table public.booking_requests
  drop constraint if exists booking_requests_rate_mode_check;

alter table public.booking_requests
  add constraint booking_requests_rate_mode_check
  check (rate_mode in ('fixed', 'open'));

alter table public.booking_requests
  drop constraint if exists booking_requests_proposed_rate_status_check;

alter table public.booking_requests
  add constraint booking_requests_proposed_rate_status_check
  check (proposed_rate_status is null or proposed_rate_status in ('pending', 'accepted', 'declined'));

alter table public.booking_requests
  drop constraint if exists booking_requests_proposed_rate_note_length_check;

alter table public.booking_requests
  add constraint booking_requests_proposed_rate_note_length_check
  check (proposed_rate_note is null or char_length(proposed_rate_note) <= 250);

create index if not exists booking_requests_conversation_id_idx
  on public.booking_requests (conversation_id);

create index if not exists booking_requests_sender_id_idx
  on public.booking_requests (sender_id);

create index if not exists booking_requests_event_id_idx
  on public.booking_requests (event_id);

-- ============================================================================
-- PUBLIC.EVENTS
-- ============================================================================

create table if not exists public.events (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz not null default now(),
  owner_id text not null,
  booking_plan_id uuid references public.booking_plans (id) on delete set null,
  name text not null,
  venue text not null,
  event_date text not null,
  set_time text not null,
  rate text not null default '',
  notes text not null default '',
  status text not null default 'draft',
  crew_chat_started_at timestamptz
);

alter table public.events
  drop constraint if exists events_status_check;

alter table public.events
  add constraint events_status_check
  check (status in ('draft', 'upcoming', 'completed', 'cancelled'));

create index if not exists events_owner_id_idx
  on public.events (owner_id);

create index if not exists events_booking_plan_id_idx
  on public.events (booking_plan_id);

-- ============================================================================
-- PUBLIC.MESSAGES (DM and crew chat)
-- ============================================================================

create table if not exists public.messages (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz not null default now(),
  conversation_id uuid references public.conversations (id) on delete cascade,
  event_id uuid references public.events (id) on delete cascade,
  user_id text not null,
  body text not null,
  file_url text,
  attachment_url text
);

create index if not exists messages_conversation_id_idx
  on public.messages (conversation_id);

create index if not exists messages_event_id_idx
  on public.messages (event_id);

create index if not exists messages_user_id_idx
  on public.messages (user_id);

-- ============================================================================
-- PUBLIC.MESSAGE_REACTIONS
-- ============================================================================

create table if not exists public.message_reactions (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz not null default now(),
  message_id uuid not null references public.messages (id) on delete cascade,
  user_id text not null,
  emoji text not null,
  unique (message_id, user_id, emoji)
);

create index if not exists message_reactions_message_id_idx
  on public.message_reactions (message_id);

create index if not exists message_reactions_user_id_idx
  on public.message_reactions (user_id);

-- ============================================================================
-- PUBLIC.MESSAGE_ATTACHMENTS (DM file attachments)
-- ============================================================================

create table if not exists public.message_attachments (
  id uuid primary key default gen_random_uuid(),
  message_id uuid not null references public.messages (id) on delete cascade,
  conversation_id uuid not null,
  uploader_id text not null,
  file_url text not null,
  file_name text not null,
  file_type text not null,
  file_size integer,
  created_at timestamptz not null default now()
);

create index if not exists message_attachments_message_id_idx
  on public.message_attachments (message_id);

create index if not exists message_attachments_conversation_id_idx
  on public.message_attachments (conversation_id);

-- ============================================================================
-- PUBLIC.NOTIFICATIONS
-- ============================================================================

create table if not exists public.notifications (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz not null default now(),
  user_id text not null,
  type text not null,
  title text not null,
  body text,
  link text,
  read boolean not null default false
);

alter table public.notifications
  drop constraint if exists notifications_type_check;

alter table public.notifications
  add constraint notifications_type_check
  check (type in ('message', 'booking_request', 'booking_update'));

create index if not exists notifications_user_id_read_idx
  on public.notifications (user_id, read);

create index if not exists notifications_user_id_type_read_idx
  on public.notifications (user_id, type, read);

-- ============================================================================
-- PUBLIC.EVENT_RUN_SHEET_COLUMNS
-- ============================================================================

create table if not exists public.event_run_sheet_columns (
  id uuid primary key default gen_random_uuid(),
  event_id uuid not null references public.events (id) on delete cascade,
  owner_id text not null,
  name text not null,
  sort_order integer not null default 0
);

create index if not exists event_run_sheet_columns_event_id_idx
  on public.event_run_sheet_columns (event_id);

-- ============================================================================
-- PUBLIC.EVENT_RUN_SHEET_ROWS (CORRECTED: full definition from setupEventRunSheet.sql)
-- ============================================================================

create table if not exists public.event_run_sheet_rows (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz not null default now(),
  event_id uuid not null references public.events (id) on delete cascade,
  owner_id text not null,
  sort_order integer not null default 0,
  artist_name text not null default '',
  start_time text not null default '',
  finish_time text not null default '',
  stage_area text not null default '',
  notes text not null default '',
  booking_request_id uuid references public.booking_requests (id) on delete set null,
  custom_data jsonb not null default '{}'::jsonb
);

create index if not exists event_run_sheet_rows_event_id_idx
  on public.event_run_sheet_rows (event_id);

create index if not exists event_run_sheet_rows_booking_request_id_idx
  on public.event_run_sheet_rows (booking_request_id);

create unique index if not exists event_run_sheet_rows_event_booking_request_uidx
  on public.event_run_sheet_rows (event_id, booking_request_id)
  where booking_request_id is not null;

-- ============================================================================
-- HELPER FUNCTIONS
-- ============================================================================

-- Current authenticated user ID
create or replace function public.auth_user_id()
returns text
language sql
stable
set search_path = public
as $$
  select auth.uid()::text;
$$;

-- Check if user is member of a conversation
create or replace function public.is_conversation_member(p_conversation_id uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.conversation_members cm
    where cm.conversation_id = p_conversation_id
      and cm.user_id = auth.uid()::text
  );
$$;

-- Check if two users are both members of the same conversation
create or replace function public.is_conversation_participant(
  p_conversation_id uuid,
  p_other_user_id text
)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.conversation_members cm_self
    join public.conversation_members cm_other
      on cm_self.conversation_id = cm_other.conversation_id
    where cm_self.conversation_id = p_conversation_id
      and cm_self.user_id = auth.uid()::text
      and cm_other.user_id = p_other_user_id
  );
$$;

-- Check if user is event owner or accepted crew DJ
create or replace function public.is_event_crew_participant(
  p_event_id uuid,
  p_user_id text
)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.events e
    where e.id = p_event_id
      and e.owner_id = p_user_id
  )
  or exists (
    select 1
    from public.booking_requests br
    where br.event_id = p_event_id
      and br.recipient_id = p_user_id
      and br.status = 'accepted'
  );
$$;

-- Check if current user is event crew member
create or replace function public.is_event_crew_member(p_event_id uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select public.is_event_crew_participant(p_event_id, public.auth_user_id());
$$;

-- Count accepted crew DJs for an event
create or replace function public.count_event_accepted_crew_djs(p_event_id uuid)
returns integer
language sql
stable
security definer
set search_path = public
as $$
  select count(*)::integer
  from public.booking_requests br
  where br.event_id = p_event_id
    and br.status = 'accepted';
$$;

-- Check if user is event run sheet owner
create or replace function public.is_event_run_sheet_owner(p_event_id uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.events e
    where e.id = p_event_id
      and e.owner_id = public.auth_user_id()
  );
$$;

-- Check if user can view event run sheet
create or replace function public.can_view_event_run_sheet(p_event_id uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select public.is_event_run_sheet_owner(p_event_id)
    or public.is_event_crew_participant(p_event_id, public.auth_user_id());
$$;

-- Check if current user is event crew member (with message context)
create or replace function public.is_event_crew_member_for_message(p_event_id text)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select
    p_event_id is not null
    and btrim(p_event_id) <> ''
    and p_event_id ~ '^[0-9a-fA-F-]{36}$'
    and public.is_event_crew_member(p_event_id::uuid);
$$;

-- Get all crew participant IDs for an event
create or replace function public.get_event_crew_participant_ids(p_event_id uuid)
returns setof text
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.is_event_crew_member(p_event_id) then
    raise exception 'Not allowed to read event crew participants';
  end if;

  return query
  select e.owner_id
  from public.events e
  where e.id = p_event_id

  union

  select br.recipient_id
  from public.booking_requests br
  where br.event_id = p_event_id
    and br.status = 'accepted';
end;
$$;

-- Secure RPC: Create or return 1:1 DM conversation
create or replace function public.start_dm(p_target_user_id text)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  v_current_user_id text := public.auth_user_id();
  v_conversation_id uuid;
begin
  if v_current_user_id is null then
    raise exception 'Not authenticated';
  end if;

  if p_target_user_id is null or btrim(p_target_user_id) = '' then
    raise exception 'Invalid target user';
  end if;

  if p_target_user_id = v_current_user_id then
    raise exception 'Cannot start a DM with yourself';
  end if;

  select cm_self.conversation_id
  into v_conversation_id
  from public.conversation_members cm_self
  join public.conversation_members cm_other
    on cm_self.conversation_id = cm_other.conversation_id
  where cm_self.user_id = v_current_user_id
    and cm_other.user_id = p_target_user_id
  order by cm_self.conversation_id
  limit 1;

  if v_conversation_id is not null then
    return v_conversation_id;
  end if;

  insert into public.conversations default values
  returning id into v_conversation_id;

  insert into public.conversation_members (conversation_id, user_id)
  values
    (v_conversation_id, v_current_user_id),
    (v_conversation_id, p_target_user_id);

  return v_conversation_id;
end;
$$;

-- Secure RPC: Create notification (5-arg version for migrations 001-007)
-- Migration 008 will replace this with a 6-arg version
create or replace function public.create_notification(
  p_user_id text,
  p_type text,
  p_title text,
  p_body text default null,
  p_link text default null
)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  v_sender_id text := public.auth_user_id();
  v_notification_id uuid;
  v_conversation_id uuid;
begin
  if v_sender_id is null then
    raise exception 'Not authenticated';
  end if;

  if p_user_id is null or btrim(p_user_id) = '' then
    raise exception 'Invalid notification recipient';
  end if;

  if p_user_id = v_sender_id then
    raise exception 'Cannot create notification for yourself';
  end if;

  if p_type not in ('message', 'booking_request', 'booking_update') then
    raise exception 'Invalid notification type';
  end if;

  if p_type = 'message' then
    if p_link is null or p_link !~ '^/dm/[0-9a-fA-F-]{36}$' then
      raise exception 'Invalid message notification link';
    end if;

    v_conversation_id := substring(p_link from '^/dm/([0-9a-fA-F-]{36})$')::uuid;

    if not public.is_conversation_participant(v_conversation_id, p_user_id) then
      raise exception 'Not allowed to notify this user for this conversation';
    end if;
  elsif p_type = 'booking_request' then
    if not exists (
      select 1
      from public.booking_requests br
      where br.sender_id = v_sender_id
        and br.recipient_id = p_user_id
        and br.created_at > now() - interval '10 minutes'
    ) then
      raise exception 'Not allowed to create booking_request notification';
    end if;
  elsif p_type = 'booking_update' then
    if not exists (
      select 1
      from public.booking_requests br
      where br.recipient_id = v_sender_id
        and br.sender_id = p_user_id
        and br.status in ('accepted', 'declined')
    ) then
      raise exception 'Not allowed to create booking_update notification';
    end if;
  end if;

  insert into public.notifications (user_id, type, title, body, link, read)
  values (p_user_id, p_type, p_title, p_body, p_link, false)
  returning id into v_notification_id;

  return v_notification_id;
end;
$$;

-- ============================================================================
-- ROW LEVEL SECURITY: ENABLE RLS ON ALL TABLES
-- ============================================================================

alter table public.users enable row level security;
alter table public.booking_plans enable row level security;
alter table public.booking_requests enable row level security;
alter table public.conversations enable row level security;
alter table public.conversation_members enable row level security;
alter table public.messages enable row level security;
alter table public.notifications enable row level security;
alter table public.message_reactions enable row level security;
alter table public.message_attachments enable row level security;
alter table public.events enable row level security;
alter table public.event_run_sheet_columns enable row level security;
alter table public.event_run_sheet_rows enable row level security;

-- ============================================================================
-- RLS POLICIES
-- ============================================================================

-- PUBLIC.USERS — Authenticated read all, insert/update own
drop policy if exists "users_select_authenticated" on public.users;
drop policy if exists "users_insert_own" on public.users;
drop policy if exists "users_update_own" on public.users;

create policy "users_select_authenticated"
  on public.users
  for select
  to authenticated
  using (auth.uid() is not null);

create policy "users_insert_own"
  on public.users
  for insert
  to authenticated
  with check (user_id = public.auth_user_id());

create policy "users_update_own"
  on public.users
  for update
  to authenticated
  using (user_id = public.auth_user_id())
  with check (user_id = public.auth_user_id());

-- PUBLIC.BOOKING_PLANS — Authenticated: select own, insert own, update own, delete own
drop policy if exists "booking_plans_select_own" on public.booking_plans;
drop policy if exists "booking_plans_insert_own" on public.booking_plans;
drop policy if exists "booking_plans_update_own" on public.booking_plans;
drop policy if exists "booking_plans_delete_own" on public.booking_plans;

create policy "booking_plans_select_own"
  on public.booking_plans
  for select
  to authenticated
  using (owner_id = public.auth_user_id());

create policy "booking_plans_insert_own"
  on public.booking_plans
  for insert
  to authenticated
  with check (owner_id = public.auth_user_id());

create policy "booking_plans_update_own"
  on public.booking_plans
  for update
  to authenticated
  using (owner_id = public.auth_user_id())
  with check (owner_id = public.auth_user_id());

create policy "booking_plans_delete_own"
  on public.booking_plans
  for delete
  to authenticated
  using (owner_id = public.auth_user_id());

-- PUBLIC.BOOKING_REQUESTS — Authenticated: select if participant, insert if sender, update based on role
drop policy if exists "booking_requests_select_participant" on public.booking_requests;
drop policy if exists "booking_requests_insert_sender" on public.booking_requests;
drop policy if exists "booking_requests_update_recipient" on public.booking_requests;
drop policy if exists "booking_requests_update_sender_cancel" on public.booking_requests;
drop policy if exists "booking_requests_update_sender_archive" on public.booking_requests;

create policy "booking_requests_select_participant"
  on public.booking_requests
  for select
  to authenticated
  using (
    sender_id = public.auth_user_id()
    or recipient_id = public.auth_user_id()
  );

create policy "booking_requests_insert_sender"
  on public.booking_requests
  for insert
  to authenticated
  with check (
    sender_id = public.auth_user_id()
    and recipient_id <> public.auth_user_id()
    and public.is_conversation_member(conversation_id)
  );

create policy "booking_requests_update_recipient"
  on public.booking_requests
  for update
  to authenticated
  using (
    recipient_id = public.auth_user_id()
    and status = 'pending'
  )
  with check (
    recipient_id = public.auth_user_id()
    and status in ('accepted', 'declined')
  );

create policy "booking_requests_update_sender_cancel"
  on public.booking_requests
  for update
  to authenticated
  using (
    sender_id = public.auth_user_id()
    and status = 'pending'
  )
  with check (
    sender_id = public.auth_user_id()
    and status = 'cancelled'
  );

create policy "booking_requests_update_sender_archive"
  on public.booking_requests
  for update
  to authenticated
  using (
    sender_id = public.auth_user_id()
    and status = 'cancelled'
  )
  with check (
    sender_id = public.auth_user_id()
    and status = 'cancelled'
  );

-- PUBLIC.EVENTS — Authenticated: select if owner or invited, insert/update if owner, delete if owner
drop policy if exists "events_select_owner_or_invited" on public.events;
drop policy if exists "events_insert_owner" on public.events;
drop policy if exists "events_update_owner" on public.events;
drop policy if exists "events_delete_owner" on public.events;

create policy "events_select_owner_or_invited"
  on public.events
  for select
  to authenticated
  using (
    owner_id = public.auth_user_id()
    or exists (
      select 1
      from public.booking_requests br
      where br.event_id = events.id
        and br.recipient_id = public.auth_user_id()
    )
  );

create policy "events_insert_owner"
  on public.events
  for insert
  to authenticated
  with check (
    owner_id = public.auth_user_id()
    and (
      booking_plan_id is null
      or exists (
        select 1
        from public.booking_plans bp
        where bp.id = booking_plan_id
          and bp.owner_id = public.auth_user_id()
      )
    )
  );

create policy "events_update_owner"
  on public.events
  for update
  to authenticated
  using (owner_id = public.auth_user_id())
  with check (
    owner_id = public.auth_user_id()
    and (
      booking_plan_id is null
      or exists (
        select 1
        from public.booking_plans bp
        where bp.id = booking_plan_id
          and bp.owner_id = public.auth_user_id()
      )
    )
  );

create policy "events_delete_owner"
  on public.events
  for delete
  to authenticated
  using (owner_id = public.auth_user_id());

-- PUBLIC.CONVERSATIONS — Authenticated: select if member
drop policy if exists "conversations_select_member" on public.conversations;

create policy "conversations_select_member"
  on public.conversations
  for select
  to authenticated
  using (public.is_conversation_member(id));

-- PUBLIC.CONVERSATION_MEMBERS — Authenticated: select if member of conversation
drop policy if exists "conversation_members_select_shared" on public.conversation_members;

create policy "conversation_members_select_shared"
  on public.conversation_members
  for select
  to authenticated
  using (public.is_conversation_member(conversation_id));

-- PUBLIC.MESSAGES — Authenticated: select if in conversation or event crew, insert if sender and member
drop policy if exists "messages_select_conversation_member" on public.messages;
drop policy if exists "messages_insert_conversation_sender" on public.messages;
drop policy if exists "messages_update_conversation_member" on public.messages;
drop policy if exists "messages_select_event_authenticated" on public.messages;
drop policy if exists "messages_insert_event_sender" on public.messages;

create policy "messages_select_conversation_member"
  on public.messages
  for select
  to authenticated
  using (
    conversation_id is not null
    and public.is_conversation_member(conversation_id)
  );

create policy "messages_insert_conversation_sender"
  on public.messages
  for insert
  to authenticated
  with check (
    conversation_id is not null
    and user_id = public.auth_user_id()
    and public.is_conversation_member(conversation_id)
  );

create policy "messages_update_conversation_member"
  on public.messages
  for update
  to authenticated
  using (
    conversation_id is not null
    and public.is_conversation_member(conversation_id)
  )
  with check (
    conversation_id is not null
    and public.is_conversation_member(conversation_id)
  );

create policy "messages_select_event_authenticated"
  on public.messages
  for select
  to authenticated
  using (
    event_id is not null
    and public.is_event_crew_member_for_message(event_id::text)
  );

create policy "messages_insert_event_sender"
  on public.messages
  for insert
  to authenticated
  with check (
    event_id is not null
    and user_id = public.auth_user_id()
  );

-- PUBLIC.NOTIFICATIONS — Authenticated: select own, update own
drop policy if exists "notifications_select_own" on public.notifications;
drop policy if exists "notifications_update_own" on public.notifications;

create policy "notifications_select_own"
  on public.notifications
  for select
  to authenticated
  using (user_id = public.auth_user_id());

create policy "notifications_update_own"
  on public.notifications
  for update
  to authenticated
  using (user_id = public.auth_user_id())
  with check (user_id = public.auth_user_id());

-- PUBLIC.MESSAGE_REACTIONS — Authenticated: select if in conversation, insert if sender
drop policy if exists "message_reactions_select_conversation" on public.message_reactions;
drop policy if exists "message_reactions_insert_sender" on public.message_reactions;

create policy "message_reactions_select_conversation"
  on public.message_reactions
  for select
  to authenticated
  using (
    exists (
      select 1 from public.messages m
      where m.id = message_id
        and (
          (m.conversation_id is not null and public.is_conversation_member(m.conversation_id))
          or m.event_id is not null
        )
    )
  );

create policy "message_reactions_insert_sender"
  on public.message_reactions
  for insert
  to authenticated
  with check (user_id = public.auth_user_id());

-- PUBLIC.MESSAGE_ATTACHMENTS — Authenticated: select if member, insert if uploader and member
drop policy if exists "message_attachments_select_member" on public.message_attachments;
drop policy if exists "message_attachments_insert_uploader" on public.message_attachments;

create policy "message_attachments_select_member"
  on public.message_attachments
  for select
  to authenticated
  using (public.is_conversation_member(conversation_id));

create policy "message_attachments_insert_uploader"
  on public.message_attachments
  for insert
  to authenticated
  with check (
    uploader_id = public.auth_user_id()
    and public.is_conversation_member(conversation_id)
    and exists (
      select 1
      from public.messages m
      where m.id = message_id
        and m.conversation_id = message_attachments.conversation_id
        and m.user_id = public.auth_user_id()
    )
  );

-- PUBLIC.EVENT_RUN_SHEET_COLUMNS & ROWS — Authenticated: select if can view
drop policy if exists "event_run_sheet_columns_select_crew" on public.event_run_sheet_columns;
drop policy if exists "event_run_sheet_rows_select_crew" on public.event_run_sheet_rows;

create policy "event_run_sheet_columns_select_crew"
  on public.event_run_sheet_columns
  for select
  to authenticated
  using (
    exists (
      select 1 from public.events e
      where e.id = event_id
        and public.can_view_event_run_sheet(e.id)
    )
  );

create policy "event_run_sheet_rows_select_crew"
  on public.event_run_sheet_rows
  for select
  to authenticated
  using (
    exists (
      select 1 from public.events e
      where e.id = event_id
        and public.can_view_event_run_sheet(e.id)
    )
  );

-- ============================================================================
-- GRANTS: DENY ANON, ALLOW AUTHENTICATED
-- ============================================================================

revoke all on table public.users from anon;
revoke all on table public.booking_plans from anon;
revoke all on table public.booking_requests from anon;
revoke all on table public.conversations from anon;
revoke all on table public.conversation_members from anon;
revoke all on table public.messages from anon;
revoke all on table public.notifications from anon;
revoke all on table public.message_reactions from anon;
revoke all on table public.message_attachments from anon;
revoke all on table public.events from anon;
revoke all on table public.event_run_sheet_columns from anon;
revoke all on table public.event_run_sheet_rows from anon;

-- Authenticated grants (specific operations only)
grant select, insert, update on table public.users to authenticated;
grant select, insert, update, delete on table public.booking_plans to authenticated;
grant select, insert, update on table public.booking_requests to authenticated;
grant select on table public.conversations to authenticated;
grant select on table public.conversation_members to authenticated;
grant select, insert, update on table public.messages to authenticated;
grant select, update on table public.notifications to authenticated;
grant select, insert, update, delete on table public.message_reactions to authenticated;
grant select, insert on table public.message_attachments to authenticated;
grant select, insert, update, delete on table public.events to authenticated;
grant select, insert, update, delete on table public.event_run_sheet_columns to authenticated;
grant select, insert, update, delete on table public.event_run_sheet_rows to authenticated;

-- DM creation: INSERT only via start_dm() RPC, not direct table INSERT
revoke insert on table public.conversations from authenticated;
revoke insert on table public.conversation_members from authenticated;

-- Notification creation: INSERT only via create_notification() RPC, not direct table INSERT
revoke insert on table public.notifications from authenticated;

-- ============================================================================
-- FUNCTION GRANTS
-- ============================================================================

revoke all on function public.auth_user_id() from public;
revoke all on function public.is_conversation_member(uuid) from public;
revoke all on function public.is_conversation_participant(uuid, text) from public;
revoke all on function public.is_event_crew_participant(uuid, text) from public;
revoke all on function public.is_event_crew_member(uuid) from public;
revoke all on function public.count_event_accepted_crew_djs(uuid) from public;
revoke all on function public.is_event_run_sheet_owner(uuid) from public;
revoke all on function public.can_view_event_run_sheet(uuid) from public;
revoke all on function public.is_event_crew_member_for_message(text) from public;
revoke all on function public.get_event_crew_participant_ids(uuid) from public;
revoke all on function public.start_dm(text) from public;
revoke all on function public.create_notification(text, text, text, text, text) from public;

grant execute on function public.auth_user_id() to authenticated;
grant execute on function public.is_conversation_member(uuid) to authenticated;
grant execute on function public.is_conversation_participant(uuid, text) to authenticated;
grant execute on function public.is_event_crew_participant(uuid, text) to authenticated;
grant execute on function public.is_event_crew_member(uuid) to authenticated;
grant execute on function public.count_event_accepted_crew_djs(uuid) to authenticated;
grant execute on function public.is_event_run_sheet_owner(uuid) to authenticated;
grant execute on function public.can_view_event_run_sheet(uuid) to authenticated;
grant execute on function public.is_event_crew_member_for_message(text) to authenticated;
grant execute on function public.get_event_crew_participant_ids(uuid) to authenticated;
grant execute on function public.start_dm(text) to authenticated;
grant execute on function public.create_notification(text, text, text, text, text) to authenticated;

-- ============================================================================
-- SCHEMA REFRESH
-- ============================================================================

notify pgrst, 'reload schema';
